### PR TITLE
Spanish [ES] translation files added

### PR DESCRIPTION
**Pull request by AkemiKami201**
Added file _es.yml_ and _blu_es.yml_
Since my language is not Mandarin, there may be some mistakes, but I made it understandable for Spanish people.

### CODE REVIEW

**Comment by txperl** [comment]
Merged. Thanks again!

These changes will be included into the next version.

Have a nice day. 😄

**Comment by txperl** [comment]
Because of the base design of program, PixivBiu is a bit weak in multilingualism. There will be many steps to do if I want to fix it, but I will try some simple and direct ways first, especially in the webpage.

**Comment by txperl** [comment]
By the way, I think it's a good method handled by you, that create a new language-specific config file and guide users who know Spanish to it. I will "copy it" to the English and Japanese ones.

**Comment by AkemiKami201** [comment]
> Because of the base design of program, PixivBiu is a bit weak in multilingualism. There will be many steps to do if I want to fix it, but I will try some simple and direct ways first, especially in the webpage.

If you wish, I can help you translate the website into English or Spanish.

**Pull request merged**
